config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  root to: "flashcards#index"
  
  resources :flashcards do
    resources :words
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
  belongs_to :user
  has_many :words
  with_options presence: true do
    validates :name,      length: { maximum: 100 }
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :flashcards
  has_many :words
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :email,   format: {with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i}
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :flashcard

  with_options presence: true do
    validates :name,      length: { maximum: 100 }
    validates :meaning,   length: { maximum: 200 }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configre_permitted_parameters, if: :devise_controller?

  def configre_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  def index
    @flashcards = Flashcard.all
  end

  def new
    @flashcard = Flashcard.new
  end

  def create
    @flashcard = Flashcard.new(flashcard_palams)
    if @flashcard.save
      redirect_to new_flashcard_word_path(@flashcard.id)
    else
      render 'index'
    end
  end


  private
  def flashcard_palams
    # binding.pry
    params.permit(:name, :user_id).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user.create(user_params)
  end

  private
  def user_params
    params.require(:user).permit(:nickname, :eamil, :password)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController

  def new
    # @flashcard = Flashcard.find(params[:id])
    @word = Word.new
  end

  def create
    @word = Word.create(word_params)
    if @word.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  private
  def word_params
    params.require(:word).permit(:name, :meaning).merge(flashcard_id: params[:flashcard_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/flashcards/index.html.erb
<header class="top-header">
  <div class="left-header">
    <div class="logo">
      <%= link_to 'flashcard', "#"%>
    </div>
  </div>
  <div class="right-header">
    <ul class="list">
      <li> <%= link_to 'nickname', "#"%> </li>
      <li> <%= link_to 'ログアウト', "#"%> </li>
      <li> <%= link_to 'ログイン', "#"%> </li>
      <li> <%= link_to '新規登録', "#"%> </li>
    </ul>
  </div>
</header>

<body>
  <div class="main">
    <%# 単語一覧 %>
    <div class="card-list">
      <h1>単語帳一覧</h1>
      <ul class="cards">
         <% @flashcards.each do |flashcards| %>
          <li><%= link_to flashcards.name, flashcard_words_path(flashcards.id), class: "content" %></li>
        <% end %>
      </ul>
    </div>

    <%# 登録機能 %>
    <div>
      <h2>単語帳登録</h2>
      <%= form_with model: @flashcard, url: flashcards_path, local: true do |f|%>
      <%= f.text_field :name, placeholder: "単語帳名"%>
      <%= f.submit "登録"%>
      <% end %>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashcardApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/words/new.html.erb
<div class="word-register-main">

  <h2 class="word-register-title">単語登録</h2>
  <%= form_with model: @word, url: flashcard_words_path,local: true do |f|%>

    <div class="word-title">
      単語名
    </div>
      <%= f.text_area :name, class: "word-name", placeholder:"単語"%>
    <div class="word-title">
      単語　意味
    </div>
      <%= f.text_area :meaning, clss: "word-meaning", placeholder: "単語意味"%>
    
    <%= f.submit "登録する",　class:"register-btn"%>

    </div>
  <% end %>
</div>